# Generated by Django 5.2.16 on 2026-09-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padron', '0023_rename_estadosocio_estadoadministrativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id_estado_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('archivoUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('requiere_firma', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='padron.persona')),
                ('estado_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documental.estadodocumento')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documental.tipodocumento')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
    ]
