# Generated by Django 5.2.16 on 2026-10-02 14:46

import documental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0003_alter_documento_archivourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivoUrl',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=documental.models.get_upload_path),
        ),
    ]
