# Generated by Django 5.2.16 on 2026-10-02 22:34

import django.core.validators
import documental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0004_alter_documento_archivourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivoUrl',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=documental.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
