# Generated by Django 5.2.16 on 2026-10-03 02:58

from django.db import migrations, models

from documental.models import build_nombre, resolve_estado_nombre


def regenerate_nombre_and_estado(apps, schema_editor):
    Documento = apps.get_model('documental', 'Documento')
    EstadoDocumento = apps.get_model('documental', 'EstadoDocumento')
    estados = {estado.nombre: estado for estado in EstadoDocumento.objects.filter(nombre__in=['Vigente', 'Vencido'])}

    for documento in Documento.objects.select_related('persona', 'tipo_documento'):
        documento.nombre = build_nombre(documento.persona.dni, documento.tipo_documento.nombre, documento.fecha_vencimiento)
        documento.estado_documento = estados[resolve_estado_nombre(documento.fecha_vencimiento)]
        documento.save(update_fields=['nombre', 'estado_documento'])


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0005_alter_documento_archivourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(regenerate_nombre_and_estado, migrations.RunPython.noop),
    ]
