# Generated by Django 5.2.16 on 2026-08-12 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('socio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'socio',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('jugador_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='padron.categoria')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='padron.socio')),
            ],
            options={
                'db_table': 'jugador',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('docente_id', models.AutoField(primary_key=True, serialize=False)),
                ('legajo', models.IntegerField()),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='padron.jugador')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='padron.persona')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
    ]
