# Generated by Django 5.2.16 on 2026-08-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='nombre',
        ),
        migrations.AddField(
            model_name='socio',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='padron.persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
