# Generated by Django 5.2.16 on 2026-08-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_remove_docente_jugador_remove_socio_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='telefono',
        ),
        migrations.AddField(
            model_name='jugador',
            name='contactoEmergencia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jugador',
            name='obra_social',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tallaIndumentaria',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
