# Generated by Django 5.2 on 2026-08-24 22:02

from django.apps import apps
import django.db.models.deletion
from django.db import migrations, models

ESTADOS_INICIALES = [
"Activo",
"Inactivo",
]

def crear_estados(apps, schema_editor):
    EstadoDeportivo = apps.get_model("padron", "EstadoDeportivo")
    for nombre in ESTADOS_INICIALES:
        EstadoDeportivo.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0005_alter_jugador_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDeportivo',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_deportivo',
            },
        ),
        migrations.RunPython(crear_estados),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='padron.categoria'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='padron.socio'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='padron.estadodeportivo'),
        ),
    ]
