# Generated by Django 5.2 on 2026-08-24 22:47

import django.db.models.deletion
import padron.models
from django.db import migrations, models


def crear_valores_por_defecto(apps, schema_editor):
    Categoria = apps.get_model('padron', 'Categoria')

    Categoria.objects.get_or_create(nombre='No asignado')


def conservar_valores_por_defecto(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0006_estadoderportivo_alter_jugador_options_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_valores_por_defecto, conservar_valores_por_defecto),
        migrations.AlterField(
            model_name='jugador',
            name='categoria',
            field=models.ForeignKey(default=padron.models.get_default_categoria, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='padron.categoria'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='estado',
            field=models.ForeignKey(default=padron.models.get_default_estado_deportivo, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='padron.estadodeportivo'),
        ),
    ]
