# Generated by Django 5.2.16 on 2026-08-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0007_alter_jugador_categoria_alter_jugador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='anio_vigente',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_maxima',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_minima',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
