# Generated by Django 5.2.16 on 2026-08-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0007_alter_jugador_categoria_alter_jugador_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='contactoEmergencia',
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('contacto_emergencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('responsable_legal', models.BooleanField(default=False)),
                ('relacion', models.CharField(max_length=50)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='padron.jugador')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='padron.persona')),
            ],
            options={
                'db_table': 'contacto_emergencia',
                'constraints': [models.UniqueConstraint(fields=('persona', 'jugador'), name='persona_jugador_contacto_unico')],
            },
        ),
    ]
