# Generated by Django 5.2.16 on 2026-08-28 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0008_categoria_anio_vigente_categoria_edad_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2026, 8, 28)),
            preserve_default=False,
        ),
    ]
