# Generated by Django 5.2.16 on 2026-08-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0008_remove_jugador_contactoemergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='obra_social',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='tallaIndumentaria',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
