# Generated by Django 5.2.16 on 2026-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0009_alter_jugador_obra_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='tallaIndumentaria',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
