# Generated by Django 5.2.16 on 2026-09-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0009_persona_fecha_nacimiento'),
        ('padron', '0010_alter_jugador_tallaindumentaria'),
    ]

    operations = [
    ]
