# Generated by Django 5.2.16 on 2026-09-01

from django.db import migrations, models
import padron.models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0010_alter_jugador_tallaindumentaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='anio_vigente',
            field=models.PositiveIntegerField(default=padron.models.get_anio_actual),
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_maxima',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_minima',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('nombre', 'anio_vigente', 'genero'), name='categoria_nombre_anio_genero_unico'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.CheckConstraint(check=models.Q(('edad_maxima__gte', models.F('edad_minima'))), name='categoria_edad_maxima_gte_minima'),
        ),
    ]
