# Generated by Django 5.2.16 on 2026-08-31 23:53

import django.db.models.deletion
import django.utils.timezone
import padron.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0010_alter_jugador_tallaindumentaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSocio',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_socio',
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socio',
            name='numero_socio',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='estado_socio',
            field=models.ForeignKey(default=padron.models.get_default_estado_socio, on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='padron.estadosocio'),
        ),
    ]
