# Generated by Django 5.2.16 on 2026-09-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0012_domicilio_genero_localidad_persona_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='departamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='piso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
