# Generated by Django 5.2.16 on 2026-09-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0011_categoria_anio_vigente_categoria_edad_maxima_and_more'),
        ('padron', '0013_domicilio_departamento_domicilio_piso'),
    ]

    operations = [
    ]
