# Generated by Django 5.2.16 on 2026-09-01 21:59

from django.db import migrations


def seed_data(apps, schema_editor):
    Genero = apps.get_model('padron', 'Genero')
    Localidad = apps.get_model('padron', 'Localidad')
    EstadoSocio = apps.get_model('padron', 'EstadoSocio')

    generos = ["Femenino", "Masculino"]
    for g in generos:
        Genero.objects.get_or_create(nombre=g)

    localidades = [
        ("La Plata", "1900"),
        ("Berisso", "1923"),
        ("Ensenada", "1925")
    ]
    for loc_nombre, loc_cp in localidades:
        Localidad.objects.get_or_create(nombre=loc_nombre, defaults={'codigo_postal': loc_cp})

    estados = ["Activo", "Inactivo"]
    for est in estados:
        EstadoSocio.objects.get_or_create(nombre=est)


def reverse_seed_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0014_merge_20260901_1735'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data)
    ]
