# Generated by Django 5.2.16 on 2026-09-02 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0015_seed_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
