# Generated by Django 5.2.16 on 2026-09-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0015_seed_demographics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoria',
            name='categoria_edad_maxima_gte_minima',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='edad_minima',
        ),
    ]