# Generated by Django 5.2.16 on 2026-09-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0016_remove_categoria_edad_minima'),
    ]

    operations = [
    ]
from django.db import migrations


def crear_schedules(apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')

    schedules = [
        {
            'name': 'tarea_recategorizar_jugadores',
            'func': 'padron.services.recategorizar_jugadores',
            'schedule_type': 'I',  # Minutos
            'minutes': 1,
            'repeats': -1,
        },
        {
            'name': 'tarea_pasar_anio_vigente',
            'func': 'padron.services.pasr_de_anio_vigente_a_categoria',
            'schedule_type': 'I',
            'minutes': 1,
            'repeats': -1,
        },
    ]

    for data in schedules:
        Schedule.objects.update_or_create(
            name=data['name'],
            defaults={
                'func': data['func'],
                'schedule_type': data['schedule_type'],
                'minutes': data['minutes'],
                'repeats': data['repeats'],
            },
        )


def eliminar_schedules(apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.filter(
        name__in=['tarea_recategorizar_jugadores', 'tarea_pasar_anio_vigente']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0016_remove_categoria_edad_minima'),  # Django ya lo completa solo al generar el archivo
        ('django_q', '0001_initial'),          # confirmá el nombre real con showmigrations
    ]

    operations = [
        migrations.RunPython(crear_schedules, eliminar_schedules),
    ]