# Generated by Django 5.2.16 on 2026-09-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0016_docente_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteCategoria',
            fields=[
                ('docente_categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_categoria', to='padron.categoria')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_docente', to='padron.docente')),
            ],
            options={
                'db_table': 'docente_categoria',
                'constraints': [models.UniqueConstraint(fields=('docente', 'categoria'), name='docente_categoria_unico')],
            },
        ),
    ]
