# Generated by Django 5.2.16 on 2026-09-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0017_docentecategoria'),
        ('padron', '0018_seed_categorias_lap'),
    ]

    operations = [
    ]
