# Generated by Django 5.2.16 on 2026-09-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0019_merge_0017_docentecategoria_0018_seed_categorias_lap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoemergencia',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_emergencia', to='padron.persona'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='docente', to='padron.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='socio', to='padron.persona'),
        ),
    ]
