# Generated by Django 5.2.16 on 2026-09-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0020_alter_contactoemergencia_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='categoria_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores_secundarios', to='padron.categoria'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='jugador', to='padron.socio'),
        ),
    ]
