# Generated by Django 5.2.16 on 2026-09-29 15:14

import django.db.models.deletion
import padron.models
from django.db import migrations, models


CARGOS_DOCENTE = [
    "Profesor de educación física",
    "Entrenador de arqueros",
    "Director técnico o formador",
    "Ayudante técnico",
]


def seed_cargos(apps, schema_editor):
    CargoDocente = apps.get_model('padron', 'CargoDocente')
    for nombre in CARGOS_DOCENTE:
        CargoDocente.objects.get_or_create(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0021_jugador_categoria_secundaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDocente',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cargo_docente',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.ForeignKey(default=padron.models.get_default_estado_socio, on_delete=django.db.models.deletion.PROTECT, related_name='docentes', to='padron.estadosocio'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='legajo',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='docentecategoria',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='padron.cargodocente'),
        ),
        migrations.RunPython(seed_cargos, migrations.RunPython.noop),
    ]
