# Generated by Django 5.2.16 on 2026-09-29 18:27
# Editada a mano: ContactoEmergencia -> VinculoFamiliar se hace con renames
# (en lugar de Delete/Create) para conservar los datos existentes.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0022_docente_cargo_estado_legajo'),
    ]

    operations = [
        # EstadoSocio -> EstadoAdministrativo
        migrations.RenameModel(
            old_name='EstadoSocio',
            new_name='EstadoAdministrativo',
        ),
        migrations.AlterModelTable(
            name='estadoadministrativo',
            table='estado_administrativo',
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='estado_socio',
            new_name='estado_administrativo',
        ),

        # Talle de indumentaria
        migrations.AlterField(
            model_name='jugador',
            name='tallaIndumentaria',
            field=models.CharField(blank=True, choices=[('XS', 'Extra chica'), ('S', 'Chica'), ('M', 'Mediana'), ('L', 'Grande'), ('XL', 'Extra grande'), ('XXL', 'Doble extra grande')], default='', max_length=3),
        ),

        # ContactoEmergencia -> VinculoFamiliar
        migrations.RenameModel(
            old_name='ContactoEmergencia',
            new_name='VinculoFamiliar',
        ),
        migrations.AlterModelTable(
            name='vinculofamiliar',
            table='vinculo_familiar',
        ),
        migrations.RenameField(
            model_name='vinculofamiliar',
            old_name='contacto_emergencia_id',
            new_name='vinculo_familiar_id',
        ),
        migrations.AlterField(
            model_name='vinculofamiliar',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_familiares', to='padron.persona'),
        ),
        migrations.AlterField(
            model_name='vinculofamiliar',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_familiares', to='padron.jugador'),
        ),
    ]
