/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#a5acc5",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#131b2e",
        "tertiary-fixed": "#dae2fd",
        "on-secondary-container": "#00476e",
        "background": "#f8f9ff",
        "on-tertiary-container": "#384055",
        "surface-variant": "#d3e4fe",
        "secondary": "#006398",
        "surface": "#f8f9ff",
        "secondary-fixed": "#cce5ff",
        "surface-container-high": "#dce9ff",
        "secondary-container": "#5bb8fe",
        "primary-fixed": "#cae6ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#93ccff",
        "inverse-primary": "#8ccdff",
        "on-primary-container": "#004566",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#004b70",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "primary": "#006493",
        "surface-tint": "#006493",
        "surface-bright": "#f8f9ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#001e30",
        "surface-dim": "#cbdbf5",
        "primary-container": "#38b6ff",
        "primary-fixed-dim": "#8ccdff",
        "outline": "#6e7882",
        "surface-container": "#e5eeff",
        "outline-variant": "#bec8d2",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3e4850",
        "on-secondary-fixed": "#001d31",
        "inverse-surface": "#213145",
        "tertiary": "#565e74",
        "on-secondary-fixed-variant": "#004b73",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#3f465c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xl": "2rem",
        "margin": "2rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-md": ["Inter"],
        "title-md": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "fontWeight": "600" }],
        "display-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-md": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }]
      }
    },
  },
}