from django.urls import path

from .views import (
    categoria_detail,
    categoria_list_create,
    docente_detail,
    docente_list_create,
    estado_detail,
    estado_list_create,
    jugador_detail,
    jugador_list_create,
    persona_detail,
    persona_list_create,
    socio_detail,
    socio_list_create,
    contacto_emergencia_list_create,
    contacto_emergencia_detail,
    estado_socio_list_create,
    estado_socio_detail,
    genero_list,
    localidad_list,
)

urlpatterns = [
    path("persona/", persona_list_create, name="persona-list"),
    path("persona/<int:pk>/", persona_detail, name="persona-detail"),
    path("socio/", socio_list_create, name="socio-list"),
    path("socio/<int:pk>/", socio_detail, name="socio-detail"),
    path("categoria/", categoria_list_create, name="categoria-list"),
    path("categoria/<int:pk>/", categoria_detail, name="categoria-detail"),
    path("estado/", estado_list_create, name="estado-list"),
    path("estado/<int:pk>/", estado_detail, name="estado-detail"),
    path("jugador/", jugador_list_create, name="jugador-list"),
    path("jugador/<int:pk>/", jugador_detail, name="jugador-detail"),
    path("docente/", docente_list_create, name="docente-list"),
    path("docente/<int:pk>/", docente_detail, name="docente-detail"),
    path("contacto-emergencia/", contacto_emergencia_list_create, name="contacto-emergencia-list"),
    path("contacto-emergencia/<int:pk>/", contacto_emergencia_detail, name="contacto-emergencia-detail"),
    path("estado-socio/", estado_socio_list_create, name="estado-socio-list"),
    path("estado-socio/<int:pk>/", estado_socio_detail, name="estado-socio-detail"),
    path("genero/", genero_list, name="genero-list"),
    path("localidad/", localidad_list, name="localidad-list"),
]
