# Generated by Django 5.2.16 on 2026-09-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padron', '0019_merge_0017_docentecategoria_0018_seed_categorias_lap'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuota',
            fields=[
                ('estado_cuota_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'estado_cuota',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('cuenta_corriente_id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente', to='padron.socio')),
            ],
            options={
                'db_table': 'cuenta_corriente',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('cuota_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venc1', models.DateField()),
                ('fecha_venc2', models.DateField()),
                ('periodo', models.CharField(max_length=20)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='padron.socio')),
                ('estado_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='finanzas.estadocuota')),
            ],
            options={
                'db_table': 'cuota',
            },
        ),
        migrations.CreateModel(
            name='ItemCuota',
            fields=[
                ('item_cuota_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=50)),
                ('es_descuento', models.BooleanField()),
                ('fecha_aplicacion', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finanzas.cuota')),
            ],
            options={
                'db_table': 'item_cuota',
            },
        ),
        migrations.CreateModel(
            name='DetalleMedioPago',
            fields=[
                ('medio_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('medio_de_pago', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_de_pago', to='finanzas.pago')),
            ],
            options={
                'db_table': 'detalle_medio_pago',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('comprobante_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('numero', models.IntegerField(unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='finanzas.pago')),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
        migrations.CreateModel(
            name='CuotaXPago',
            fields=[
                ('cuota_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_pagadas', to='finanzas.pago')),
            ],
            options={
                'db_table': 'cuota_x_pago',
                'constraints': [models.UniqueConstraint(fields=('pago', 'cuota'), name='cuota_pago_unico')],
            },
        ),
    ]
