# Generated by Django 5.2.16 on 2026-09-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuota',
            name='nombre',
            field=models.CharField(choices=[('En Fecha', 'En Fecha'), ('Vencida', 'Vencida'), ('Paga', 'Paga')], max_length=40),
        ),
    ]
