# Generated by Django 5.2.16 on 2026-09-29 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_itemcuota_concepto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado_cuota',
            field=models.CharField(choices=[('EnFecha', 'En Fecha'), ('Vencida', 'Vencida'), ('Paga', 'Paga')], default='EnFecha', max_length=40),
        ),
        migrations.RenameField(
            model_name='detallemediopago',
            old_name='medio_pago_id',
            new_name='detalle_medio_pago_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('Acreditado', 'Acreditado'), ('Anulado', 'Anulado'), ('PendienteVerificacion', 'Pendiente de verificacion')], default='Acreditado', max_length=40),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallemediopago',
            name='medio_de_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('BilleteraVirtual', 'Billetera Virtual')], default='Efectivo', max_length=40),
        ),
        migrations.AlterField(
            model_name='itemcuota',
            name='concepto',
            field=models.CharField(choices=[('CuotaSocial', 'Cuota Social'), ('CuotaDeportiva', 'Cuota Deportiva'), ('Mora', 'Mora'), ('DescuentoUnico', 'Descuento Unico'), ('Beca', 'Beca'), ('Otro', 'Otro')], default='CuotaSocial', max_length=40),
        ),
        migrations.AlterField(
            model_name='itemcuota',
            name='es_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemcuota',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('movimiento_cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('Abono', 'Abono'), ('Cargo', 'Cargo')], default='Abono', max_length=40)),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('cuenta_corriente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.cuentacorriente')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.pago')),
            ],
            options={
                'db_table': 'movimiento_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Imputacion',
            fields=[
                ('imputacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimiento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones_destino', to='finanzas.movimientocuenta')),
                ('movimiento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones_origen', to='finanzas.movimientocuenta')),
            ],
            options={
                'db_table': 'imputacion',
            },
        ),
        migrations.DeleteModel(
            name='EstadoCuota',
        ),
    ]
