# Generated by Django 5.2.16 on 2026-09-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_cuota_estado_cuota_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuotaXPago',
        ),
    ]
