import django.db.models.deletion
from django.db import migrations, models


def migrar_detalles_a_items(apps, schema_editor):
    DetalleMedioPago = apps.get_model("finanzas", "DetalleMedioPago")
    ItemPago = apps.get_model("finanzas", "ItemPago")
    database = schema_editor.connection.alias

    for detalle in DetalleMedioPago.objects.using(database).all().iterator():
        ItemPago.objects.using(database).create(
            medio_de_pago=detalle.medio_de_pago,
            pago_id=detalle.pago_id,
            monto=detalle.monto,
        )


def migrar_items_a_detalles(apps, schema_editor):
    DetalleMedioPago = apps.get_model("finanzas", "DetalleMedioPago")
    ItemPago = apps.get_model("finanzas", "ItemPago")
    database = schema_editor.connection.alias

    for item in ItemPago.objects.using(database).all().iterator():
        DetalleMedioPago.objects.using(database).create(
            medio_de_pago=item.medio_de_pago,
            pago_id=item.pago_id,
            monto=item.monto,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0007_delete_cuotaxpago"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPago",
            fields=[
                ("id_item_pago", models.AutoField(primary_key=True, serialize=False)),
                (
                    "medio_de_pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Transferencia", "Transferencia"),
                            ("BilleteraVirtual", "Billetera Virtual"),
                        ],
                        max_length=40,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_pago",
                        to="finanzas.pago",
                    ),
                ),
            ],
            options={
                "db_table": "item_pago",
            },
        ),
        migrations.RunPython(migrar_detalles_a_items, migrar_items_a_detalles),
        migrations.DeleteModel(
            name="DetalleMedioPago",
        ),
    ]# Generated by Django 5.2.16 on 2026-09-29 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_delete_cuotaxpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPago',
            fields=[
                ('id_item_pago', models.AutoField(primary_key=True, serialize=False)),
                ('medio_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('BilleteraVirtual', 'Billetera Virtual')], max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pago', to='finanzas.pago')),
            ],
            options={
                'db_table': 'item_pago',
            },
        ),
        migrations.DeleteModel(
            name='DetalleMedioPago',
        ),
    ]
