# Generated by Django 5.2.16 on 2026-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_itempago_delete_detallemediopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='estado_cuenta_corriente',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=40),
        ),
    ]
