# Generated by Django 5.2.16 on 2026-10-03 17:50

from django.db import migrations, models
from django.db.models import Max


def seed_receipt_sequence(apps, schema_editor):
    Comprobante = apps.get_model("finanzas", "Comprobante")
    SecuenciaComprobante = apps.get_model("finanzas", "SecuenciaComprobante")
    last_number = Comprobante.objects.aggregate(max_num=Max("numero"))["max_num"] or 0
    SecuenciaComprobante.objects.update_or_create(pk=1, defaults={"ultimo_numero": last_number})


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_cuentacorriente_estado_cuenta_corriente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaComprobante',
            fields=[
                ('secuencia_comprobante_id', models.AutoField(primary_key=True, serialize=False)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'secuencia_comprobante',
            },
        ),
        migrations.RunPython(seed_receipt_sequence, migrations.RunPython.noop),
    ]
