# Generated by Django 5.2.16 on 2026-10-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_remove_cuota_cuenta_corriente'),
        ('padron', '0023_rename_estadosocio_estadoadministrativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='finanzas.pago'),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_corriente', to='padron.socio'),
        ),
        migrations.AlterField(
            model_name='imputacion',
            name='movimiento_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_destino', to='finanzas.movimientocuenta'),
        ),
        migrations.AlterField(
            model_name='imputacion',
            name='movimiento_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_origen', to='finanzas.movimientocuenta'),
        ),
        migrations.AlterField(
            model_name='itempago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pago', to='finanzas.pago'),
        ),
        migrations.AlterField(
            model_name='movimientocuenta',
            name='cuenta_corriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuentacorriente'),
        ),
    ]
