# Generated by Django 5.2.16 on 2026-10-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_proteger_registros_financieros'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Anulado', 'Anulado')], default='Vigente', max_length=20),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='reemplazado_por',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplaza_a', to='finanzas.comprobante'),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
    ]
