# Generated by Django 5.2.16 on 2026-10-03 19:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_backfill_comprobantes_anulados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanciera',
            fields=[
                ('configuracion_financiera_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_cuota_social', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('monto_cuota_deportiva', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10)),
                ('dia_vencimiento_1', models.PositiveSmallIntegerField(default=10)),
                ('dia_vencimiento_2', models.PositiveSmallIntegerField(default=20)),
                ('tipo_recargo_1', models.CharField(choices=[('MontoFijo', 'Monto fijo'), ('Porcentaje', 'Porcentaje')], default='MontoFijo', max_length=20)),
                ('valor_recargo_1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tipo_recargo_2', models.CharField(choices=[('MontoFijo', 'Monto fijo'), ('Porcentaje', 'Porcentaje')], default='MontoFijo', max_length=20)),
                ('valor_recargo_2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_financieras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion_financiera',
            },
        ),
    ]
