# Generated by Django 5.2.16 on 2026-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0017_configuracion_financiera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='recargos_aplicados',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
