# Generated by Django 5.2.16 on 2026-10-03 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0019_tareas_programadas'),
        ('padron', '0023_rename_estadosocio_estadoadministrativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('beca_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(choices=[('CuotaSocial', 'Cuota Social'), ('CuotaDeportiva', 'Cuota Deportiva'), ('Mora', 'Mora'), ('DescuentoUnico', 'Descuento Unico'), ('Beca', 'Beca'), ('Otro', 'Otro')], default='CuotaSocial', max_length=40)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='becas', to='padron.socio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='becas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beca',
            },
        ),
        migrations.AddField(
            model_name='itemcuota',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finanzas.beca'),
        ),
        migrations.AddConstraint(
            model_name='beca',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('monto__isnull', False), ('porcentaje__isnull', True)), models.Q(('monto__isnull', True), ('porcentaje__isnull', False)), _connector='OR'), name='beca_monto_o_porcentaje'),
        ),
        migrations.AddConstraint(
            model_name='beca',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_aplicacion'))), name='beca_fecha_fin_posterior_a_alta'),
        ),
    ]
