# Generated by Django 5.2.16 on 2026-10-03 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0020_beca'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleImputacion',
            fields=[
                ('detalle_imputacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(choices=[('CuotaSocial', 'Cuota Social'), ('CuotaDeportiva', 'Cuota Deportiva'), ('Mora', 'Mora'), ('DescuentoUnico', 'Descuento Unico'), ('Beca', 'Beca'), ('Otro', 'Otro')], max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imputacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='finanzas.imputacion')),
            ],
            options={
                'db_table': 'detalle_imputacion',
            },
        ),
    ]
