# Generated by Django 5.2.16 on 2026-10-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0023_pago_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcuota',
            name='beca',
        ),
    ]
