# Generated by Django 5.2.16 on 2026-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0026_open_missing_current_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='concepto',
            field=models.CharField(choices=[('CuotaSocial', 'Cuota Social'), ('CuotaDeportiva', 'Cuota Deportiva'), ('Mora', 'Mora'), ('DescuentoUnico', 'Descuento único'), ('Beca', 'Beca'), ('Otro', 'Otro')], default='CuotaSocial', max_length=40),
        ),
        migrations.AlterField(
            model_name='detalleimputacion',
            name='concepto',
            field=models.CharField(choices=[('CuotaSocial', 'Cuota Social'), ('CuotaDeportiva', 'Cuota Deportiva'), ('Mora', 'Mora'), ('DescuentoUnico', 'Descuento único'), ('Beca', 'Beca'), ('Otro', 'Otro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='itemcuota',
            name='concepto',
            field=models.CharField(choices=[('CuotaSocial', 'Cuota Social'), ('CuotaDeportiva', 'Cuota Deportiva'), ('Mora', 'Mora'), ('DescuentoUnico', 'Descuento único'), ('Beca', 'Beca'), ('Otro', 'Otro')], default='CuotaSocial', max_length=40),
        ),
    ]
