# Generated by Django 5.2.16 on 2026-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0028_sync_current_account_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='concepto',
            field=models.CharField(blank=True, choices=[('CuotaSocial', 'Cuota Social'), ('CuotaDeportiva', 'Cuota Deportiva'), ('Mora', 'Mora'), ('DescuentoUnico', 'Descuento único'), ('Beca', 'Beca'), ('Otro', 'Otro')], max_length=40, null=True),
        ),
    ]
