# Generated by Django 5.2.16 on 2026-10-05 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('asunto', models.CharField(blank=True, max_length=150, null=True)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comunicaciones.canalnotificacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comunicaciones.estadonotificacion')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_contacto', models.CharField(max_length=150)),
                ('detalle_fallo', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comunicaciones.canalnotificacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comunicaciones.estadonotificacion')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='comunicaciones.notificacion')),
            ],
        ),
    ]
