# Generated by Django 5.2.16 on 2026-10-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('MAIL', 'mail')], default='WHATSAPP', max_length=20),
        ),
        migrations.AlterField(
            model_name='envionotificacion',
            name='canal',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('MAIL', 'mail')], default='WHATSAPP', max_length=20),
        ),
        migrations.AlterField(
            model_name='envionotificacion',
            name='estado',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('PROGRAMADA', 'Programada'), ('FALLIDA', 'Fallida'), ('RECIBIDO', 'Recibido'), ('LEIDO', 'Leido')], default='ENVIADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('PROGRAMADA', 'Programada'), ('FALLIDA', 'Fallida'), ('RECIBIDO', 'Recibido'), ('LEIDO', 'Leido')], default='ENVIADA', max_length=20),
        ),
        migrations.DeleteModel(
            name='CanalNotificacion',
        ),
        migrations.DeleteModel(
            name='EstadoNotificacion',
        ),
    ]
