# Generated by Django 5.2.16 on 2026-10-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0002_alter_notificacion_canal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envionotificacion',
            name='fecha_lectura',
        ),
        migrations.RemoveField(
            model_name='envionotificacion',
            name='fecha_recibido',
        ),
        migrations.AlterField(
            model_name='envionotificacion',
            name='estado',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('PROGRAMADA', 'Programada'), ('FALLIDA', 'Fallida')], default='ENVIADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('PROGRAMADA', 'Programada'), ('FALLIDA', 'Fallida')], default='ENVIADA', max_length=20),
        ),
    ]
