# Generated by Django 5.2.16 on 2026-10-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0003_remove_envionotificacion_fecha_lectura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='canal',
        ),
    ]
