# Generated by Django 5.2.16 on 2026-10-07 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0004_remove_notificacion_canal'),
        ('padron', '0024_reprogramar_pasar_anio_vigente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envionotificacion',
            name='destinatario_contacto',
        ),
        migrations.AddField(
            model_name='envionotificacion',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='padron.persona'),
            preserve_default=False,
        ),
    ]
