# Generated by Django 5.2.16 on 2026-10-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0005_remove_envionotificacion_destinatario_contacto_and_more'),
        ('padron', '0027_domicilio_barrio_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envionotificacion',
            name='persona',
        ),
        migrations.AddField(
            model_name='envionotificacion',
            name='socio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='envios_notificacion', to='padron.socio'),
            preserve_default=False,
        ),
    ]
