# Generated by Django 5.2.16 on 2026-10-06 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padron', '0024_reprogramar_pasar_anio_vigente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CometExportLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comet_exports', to='padron.jugador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comet_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de exportación a COMET',
                'verbose_name_plural': 'Logs de exportación a COMET',
                'db_table': 'comet_export_log',
                'ordering': ['-fecha'],
            },
        ),
    ]
