# Generated by Django 5.2.16 on 2026-10-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0001_initial'),
        ('padron', '0024_reprogramar_pasar_anio_vigente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CometOperationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('operacion', models.CharField(choices=[('exportar_jugador', 'Exportar jugador'), ('inscribir_jugador', 'Inscribir jugador'), ('actualizar_inscripcion', 'Actualizar inscripción'), ('finalizar_inscripcion', 'Finalizar inscripción'), ('gestionar_roster', 'Gestionar roster'), ('solicitar_participacion', 'Solicitar participación'), ('cargar_alineacion', 'Cargar alineación')], max_length=40)),
                ('referencia_externa', models.CharField(blank=True, help_text='ID del recurso en COMET (competición, equipo, partido, etc.).', max_length=80)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comet_operations', to='padron.jugador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comet_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación COMET',
                'verbose_name_plural': 'Operaciones COMET',
                'db_table': 'comet_operation_log',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='CometExportLog',
        ),
    ]
