from django.urls import path

from .views import (
    comprobante_detail,
    comprobante_list_create,
    cuenta_corriente_detail,
    cuenta_corriente_list_create,
    estado_cuenta_socio,
    cuota_detail,
    cuota_list_create,
    imputacion_detail,
    imputacion_list_create,
    item_pago_detail,
    item_pago_list_create,
    item_cuota_detail,
    item_cuota_list_create,
    movimiento_cuenta_detail,
    movimiento_cuenta_list_create,
    pago_detail,
    pago_list_create,
)

urlpatterns = [
    path("cuota/", cuota_list_create, name="cuota-list"),
    path("cuota/<int:pk>/", cuota_detail, name="cuota-detail"),
    path("item-cuota/", item_cuota_list_create, name="item-cuota-list"),
    path("item-cuota/<int:pk>/", item_cuota_detail, name="item-cuota-detail"),
    path("pago/", pago_list_create, name="pago-list"),
    path("pago/<int:pk>/", pago_detail, name="pago-detail"),
    path("item-pago/", item_pago_list_create, name="item-pago-list"),
    path("item-pago/<int:pk>/", item_pago_detail, name="item-pago-detail"),
    path("comprobante/", comprobante_list_create, name="comprobante-list"),
    path("comprobante/<int:pk>/", comprobante_detail, name="comprobante-detail"),
    path("cuenta-corriente/", cuenta_corriente_list_create, name="cuenta-corriente-list"),
    path("cuenta-corriente/<int:pk>/", cuenta_corriente_detail, name="cuenta-corriente-detail"),
    path("cuenta-corriente/socio/<int:socio_id>/", estado_cuenta_socio, name="cuenta-corriente-by-socio"),
    path("cuenta-corriente/socio/<int:socio_id>/estado/", estado_cuenta_socio, name="estado-cuenta-socio"),
    path("movimiento-cuenta/", movimiento_cuenta_list_create, name="movimiento-cuenta-list"),
    path("movimiento-cuenta/<int:pk>/", movimiento_cuenta_detail, name="movimiento-cuenta-detail"),
    path("imputacion/", imputacion_list_create, name="imputacion-list"),
    path("imputacion/<int:pk>/", imputacion_detail, name="imputacion-detail"),
]