from django.urls import path

from .views import (
    aplicar_recargos_manual,
    beca_list,
    cuota_beneficio,
    comprobante_detail,
    configuracion_financiera,
    comprobante_list,
    comprobante_pdf,
    cuenta_corriente_detail,
    current_account_list,
    corregir_pago,
    estado_cuenta_socio,
    cuota_detail,
    delinquency_report_pdf,
    cuota_list_create,
    generar_cuotas_mensuales_manual,
    imputacion_detail,
    imputacion_list,
    item_pago_detail,
    item_pago_list,
    item_cuota_detail,
    item_cuota_list_create,
    movimiento_cuenta_detail,
    movimiento_cuenta_list,
    pago_detail,
    pago_list,
    registrar_pago,
    reporte_morosidad,
)

urlpatterns = [
    path("configuracion/", configuracion_financiera, name="configuracion-financiera"),
    path("cuota/generar-mensual/", generar_cuotas_mensuales_manual, name="generar-cuotas-mensuales"),
    path("cuota/aplicar-recargos/", aplicar_recargos_manual, name="aplicar-recargos"),
    path("cuota/", cuota_list_create, name="cuota-list"),
    path("cuota/<int:pk>/", cuota_detail, name="cuota-detail"),
    path("cuota/<int:pk>/beneficio/", cuota_beneficio, name="cuota-beneficio"),
    path("beca/", beca_list, name="beca-list"),
    path("item-cuota/", item_cuota_list_create, name="item-cuota-list"),
    path("item-cuota/<int:pk>/", item_cuota_detail, name="item-cuota-detail"),
    path("pago/", pago_list, name="pago-list"),
    path("pago/registrar/", registrar_pago, name="registrar-pago"),
    path("pago/<int:pk>/corregir/", corregir_pago, name="corregir-pago"),
    path("pago/<int:pk>/", pago_detail, name="pago-detail"),
    path("item-pago/", item_pago_list, name="item-pago-list"),
    path("item-pago/<int:pk>/", item_pago_detail, name="item-pago-detail"),
    path("comprobante/", comprobante_list, name="comprobante-list"),
    path("comprobante/<int:pk>/", comprobante_detail, name="comprobante-detail"),
    path("comprobante/<int:pk>/pdf/", comprobante_pdf, name="comprobante-pdf"),
    path("cuenta-corriente/", current_account_list, name="cuenta-corriente-list"),
    path("cuenta-corriente/<int:pk>/", cuenta_corriente_detail, name="cuenta-corriente-detail"),
    path("cuenta-corriente/socio/<int:socio_id>/estado/", estado_cuenta_socio, name="estado-cuenta-socio"),
    path("morosidad/", reporte_morosidad, name="reporte-morosidad"),
    path("morosidad/pdf/", delinquency_report_pdf, name="reporte-morosidad-pdf"),
    path("movimiento-cuenta/", movimiento_cuenta_list, name="movimiento-cuenta-list"),
    path("movimiento-cuenta/<int:pk>/", movimiento_cuenta_detail, name="movimiento-cuenta-detail"),
    path("imputacion/", imputacion_list, name="imputacion-list"),
    path("imputacion/<int:pk>/", imputacion_detail, name="imputacion-detail"),
]